// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 14.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CommandCreator
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\CommandGeneratorH.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class CommandGeneratorH : CommandGeneratorHBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("   \r\n");
            this.Write(" \r\n");
            this.Write(@" 
/****************************************************************************************
*
* This code was generated by the Command Creator tool for the ChainsAPM project. 
* If manual changes are made to the code they could be lost.
* 
****************************************************************************************/ 
#pragma once
#include ""ICommand.h""

namespace Commands  
{
    class ");
            
            #line 18 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\CommandGeneratorH.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ClassName));
            
            #line default
            #line hidden
            this.Write(" :\r\n        public virtual ICommand\r\n    {\r\n\r\n\r\n    public:\r\n    ");
            
            #line 24 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\CommandGeneratorH.tt"
 foreach (var enumn in this.EnumerationList) { 
            
            #line default
            #line hidden
            this.Write("        enum class ");
            
            #line 25 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\CommandGeneratorH.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(enumn.EnumerationName));
            
            #line default
            #line hidden
            this.Write("\r\n        {\r\n");
            
            #line 27 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\CommandGeneratorH.tt"
 foreach (var enumItem in enumn.Items) { 
            
            #line default
            #line hidden
            
            #line 28 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\CommandGeneratorH.tt"
 if (enumn.Items.Last().Name != enumItem.Name) { 
            
            #line default
            #line hidden
            this.Write("          ");
            
            #line 29 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\CommandGeneratorH.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(enumItem.Name));
            
            #line default
            #line hidden
            this.Write(" = 0x");
            
            #line 29 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\CommandGeneratorH.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(enumItem.Value.ToString("x8")));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 30 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\CommandGeneratorH.tt"

} else { 
            
            #line default
            #line hidden
            this.Write("          ");
            
            #line 32 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\CommandGeneratorH.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(enumItem.Name));
            
            #line default
            #line hidden
            this.Write(" = 0x");
            
            #line 32 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\CommandGeneratorH.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(enumItem.Value.ToString("x8")));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 33 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\CommandGeneratorH.tt"
 } 
            
            #line default
            #line hidden
            
            #line 34 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\CommandGeneratorH.tt"
 } 
            
            #line default
            #line hidden
            this.Write("  \r\n        };\r\n");
            
            #line 36 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\CommandGeneratorH.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n        ");
            
            #line 38 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\CommandGeneratorH.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ClassName));
            
            #line default
            #line hidden
            this.Write("(__int64 timestamp, ");
            
            #line 38 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\CommandGeneratorH.tt"
 foreach (var cpItem in this.ClassProperties) { CreateCppSignature(cpItem, TypeMapping, this.ClassProperties.Last().Name != cpItem.Name); } 
            
            #line default
            #line hidden
            this.Write("); \r\n        ~");
            
            #line 39 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\CommandGeneratorH.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ClassName));
            
            #line default
            #line hidden
            this.Write(@"();
        virtual std::shared_ptr<std::vector<char>> Encode();
        virtual std::shared_ptr<ICommand> Decode(std::shared_ptr<std::vector<char>> &data);  
        virtual std::wstring Name();
        virtual std::wstring Description();
        virtual short Code() { return code; }

    private:

");
            
            #line 48 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\CommandGeneratorH.tt"
 
PushIndent("        ");
foreach (var cpItem in this.ClassProperties)
{
    CreateCppDeclaration(cpItem, TypeMapping);
} PopIndent(); 
            
            #line default
            #line hidden
            this.Write("        __int64 timestamp; // Always use a 64bit so the message doesn\'t change\r\n " +
                    "       std::shared_ptr<std::vector<char>> internalvector;\r\n        bool hasEncod" +
                    "ed;\r\n        short code;\r\n    };\r\n\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 3 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\SnippetIncludes.tt"

protected string TypeMapper(string typeName, Dictionary<string, string> TypeMapping) {

	if (TypeMapping.ContainsKey(typeName)) 
		return TypeMapping[typeName].ToString(); 

	return typeName; 
}

private void CreateStringListing(string varName, bool isForLoop) 
{
	var szt = isForLoop ? string.Empty : "size_t ";
	varName = isForLoop ? varName + "item" : varName;
	if (isForLoop)
		WriteLine("{0}strlen_{1} = item.length();", szt, varName);
	else
		WriteLine("{0}strlen_{1} = {1}.length();", szt, varName);
	WriteLine("{0}strbytes_{1} = (strlen_{1} * sizeof(wchar_t)) + sizeof(wchar_t);", szt, varName);

        
        #line default
        #line hidden
        
        #line 21 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\SnippetIncludes.tt"
this.Write("size += sizeof(__int32); // String Length \r\nsize += sizeof(__int64); // String Ha" +
        "sh\r\nsize += strbytes_");

        
        #line default
        #line hidden
        
        #line 24 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\SnippetIncludes.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(varName));

        
        #line default
        #line hidden
        
        #line 24 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\SnippetIncludes.tt"
this.Write("; // String Bytes\r\n");

        
        #line default
        #line hidden
        
        #line 25 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\SnippetIncludes.tt"

}

protected void CreateCppLength(ClassProperty cpItem, Dictionary<string, string> TypeMapping)
{
	string typeName = TypeMapper(cpItem.TypeName, TypeMapping);
	
	if (typeName.ToLower() == "std::wstring")
	{ 	
		CreateStringListing(cpItem.Name, false);
		WriteLine("");
	} else { 

        
        #line default
        #line hidden
        
        #line 37 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\SnippetIncludes.tt"
this.Write("size += sizeof(");

        
        #line default
        #line hidden
        
        #line 38 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\SnippetIncludes.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(typeName));

        
        #line default
        #line hidden
        
        #line 38 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\SnippetIncludes.tt"
this.Write("); // Size of ");

        
        #line default
        #line hidden
        
        #line 38 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\SnippetIncludes.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(cpItem.Name));

        
        #line default
        #line hidden
        
        #line 38 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\SnippetIncludes.tt"
this.Write("\r\n\r\n");

        
        #line default
        #line hidden
        
        #line 40 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\SnippetIncludes.tt"

	}
}

protected void CreateForLoopForString(string varName) {

        
        #line default
        #line hidden
        
        #line 45 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\SnippetIncludes.tt"
this.Write("\r\nsize_t strlen_");

        
        #line default
        #line hidden
        
        #line 47 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\SnippetIncludes.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(varName));

        
        #line default
        #line hidden
        
        #line 47 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\SnippetIncludes.tt"
this.Write("item = 0;\r\nsize_t strbytes_");

        
        #line default
        #line hidden
        
        #line 48 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\SnippetIncludes.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(varName));

        
        #line default
        #line hidden
        
        #line 48 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\SnippetIncludes.tt"
this.Write("item = 0;\r\nfor (auto item : ");

        
        #line default
        #line hidden
        
        #line 49 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\SnippetIncludes.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(varName));

        
        #line default
        #line hidden
        
        #line 49 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\SnippetIncludes.tt"
this.Write(") {\r\n");

        
        #line default
        #line hidden
        
        #line 50 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\SnippetIncludes.tt"

}


protected void CreateForLoopForTypeData(string varName) {

        
        #line default
        #line hidden
        
        #line 55 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\SnippetIncludes.tt"
this.Write("\r\nfor (auto item : ");

        
        #line default
        #line hidden
        
        #line 57 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\SnippetIncludes.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(varName));

        
        #line default
        #line hidden
        
        #line 57 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\SnippetIncludes.tt"
this.Write(") {\r\n");

        
        #line default
        #line hidden
        
        #line 58 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\SnippetIncludes.tt"

}

protected void CreateCppLengthListOrArray(ClassProperty cpItem, Dictionary<string, string> TypeMapping) 
{
	string typeName = TypeMapper(cpItem.TypeName, TypeMapping);

	if (typeName.ToLower() == "std::wstring")
	{ 	
		CreateForLoopForString(cpItem.Name);
		PushIndent("    "); 
		CreateStringListing(cpItem.Name, true);
		PopIndent(); 
		WriteLine("}"); // Terminating brace for for loop
		WriteLine(""); // Extra space for clarity
	} else { 

        
        #line default
        #line hidden
        
        #line 74 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\SnippetIncludes.tt"
this.Write("size += sizeof(");

        
        #line default
        #line hidden
        
        #line 75 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\SnippetIncludes.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(typeName));

        
        #line default
        #line hidden
        
        #line 75 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\SnippetIncludes.tt"
this.Write(") * ");

        
        #line default
        #line hidden
        
        #line 75 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\SnippetIncludes.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(cpItem.Name));

        
        #line default
        #line hidden
        
        #line 75 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\SnippetIncludes.tt"
this.Write(".size(); // Size of ");

        
        #line default
        #line hidden
        
        #line 75 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\SnippetIncludes.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(cpItem.Name));

        
        #line default
        #line hidden
        
        #line 75 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\SnippetIncludes.tt"
this.Write(" vector\r\n\r\n");

        
        #line default
        #line hidden
        
        #line 77 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\SnippetIncludes.tt"

	}
}

protected void CreateCppStringData(string varName, bool isForLoop)
{
	var szt = isForLoop ? string.Empty : "size_t ";
	varName = isForLoop ? varName + "item" : varName;
	if (isForLoop)
		WriteLine("{0}strlen_{1} = item.length();", szt, varName);
	else
		WriteLine("{0}strlen_{1} = {1}.length();", szt, varName);
	Write("{0}strbytes_{1} = (strlen_{1} * sizeof(wchar_t)) + sizeof(wchar_t);", szt, varName);

	if (isForLoop)
		WriteLine("hashout = hash(item);");
	else
		WriteLine("hashout = hash({0});", varName);

        
        #line default
        #line hidden
        
        #line 95 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\SnippetIncludes.tt"
this.Write(" \r\n\r\nmemcpy(v2, &strlen_");

        
        #line default
        #line hidden
        
        #line 97 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\SnippetIncludes.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(varName));

        
        #line default
        #line hidden
        
        #line 97 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\SnippetIncludes.tt"
this.Write(", sizeof(__int32));\r\nv2 += sizeof(__int32);\r\nmemcpy(v2, &hashout, sizeof(size_t))" +
        ";\r\nv2 += sizeof(__int64);\r\n");

        
        #line default
        #line hidden
        
        #line 101 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\SnippetIncludes.tt"

if (isForLoop)
		WriteLine("memcpy(v2, item.data(), strbytes_{0});", varName);
	else
		WriteLine("memcpy(v2, {0}.data(), strbytes_{0});", varName);

        
        #line default
        #line hidden
        
        #line 106 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\SnippetIncludes.tt"
this.Write("v2 += strbytes_");

        
        #line default
        #line hidden
        
        #line 107 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\SnippetIncludes.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(varName));

        
        #line default
        #line hidden
        
        #line 107 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\SnippetIncludes.tt"
this.Write(";\r\n");

        
        #line default
        #line hidden
        
        #line 108 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\SnippetIncludes.tt"

}

protected void CreateCppTypeData(string typeName, string varName, bool isForLoop) {
if (isForLoop)
	{

        
        #line default
        #line hidden
        
        #line 114 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\SnippetIncludes.tt"
this.Write(" \r\nmemcpy(v2, &");

        
        #line default
        #line hidden
        
        #line 115 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\SnippetIncludes.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(varName));

        
        #line default
        #line hidden
        
        #line 115 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\SnippetIncludes.tt"
this.Write(", sizeof(");

        
        #line default
        #line hidden
        
        #line 115 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\SnippetIncludes.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(typeName));

        
        #line default
        #line hidden
        
        #line 115 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\SnippetIncludes.tt"
this.Write("));\r\n");

        
        #line default
        #line hidden
        
        #line 116 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\SnippetIncludes.tt"

	} else {

        
        #line default
        #line hidden
        
        #line 118 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\SnippetIncludes.tt"
this.Write("memcpy(v2, &");

        
        #line default
        #line hidden
        
        #line 119 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\SnippetIncludes.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(varName));

        
        #line default
        #line hidden
        
        #line 119 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\SnippetIncludes.tt"
this.Write(", sizeof(");

        
        #line default
        #line hidden
        
        #line 119 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\SnippetIncludes.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(typeName));

        
        #line default
        #line hidden
        
        #line 119 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\SnippetIncludes.tt"
this.Write("));\r\n");

        
        #line default
        #line hidden
        
        #line 120 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\SnippetIncludes.tt"

	}

        
        #line default
        #line hidden
        
        #line 122 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\SnippetIncludes.tt"
this.Write(" \r\nv2 += sizeof(");

        
        #line default
        #line hidden
        
        #line 123 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\SnippetIncludes.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(typeName));

        
        #line default
        #line hidden
        
        #line 123 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\SnippetIncludes.tt"
this.Write(");\r\n");

        
        #line default
        #line hidden
        
        #line 124 "C:\Users\pjld\Source\Repos\chainsapm\CommandCreator\SnippetIncludes.tt"

}

protected void CreateCppDataInsert(ClassProperty cpItem, Dictionary<string, string> TypeMapping) {

	string typeName = TypeMapper(cpItem.TypeName, TypeMapping);
	if (typeName.ToLower() == "std::wstring") {
		CreateCppStringData(cpItem.Name, false);
	} else { 
		CreateCppTypeData(typeName, cpItem.Name, false);
	} 
}

protected void CreateCppDataInsertForList(ClassProperty cpItem, Dictionary<string, string> TypeMapping) {

	string typeName = TypeMapper(cpItem.TypeName, TypeMapping);
	if (typeName.ToLower() == "std::wstring") {
		CreateForLoopForString(cpItem.Name);
		PushIndent("    "); 
		CreateCppStringData(cpItem.Name, true);
	} else { 
		
		CreateForLoopForTypeData(cpItem.Name);
		PushIndent("    "); 
		CreateCppTypeData(typeName, "item", true);
	} 
	PopIndent(); 
	WriteLine("}"); // Terminating brace for for loop
	WriteLine(""); // Extra space for clarity
}

protected void CreateCppSignature(ClassProperty cpItem, Dictionary<string, string> TypeMapping, bool isNotLast) 
{
	string typeName = TypeMapper(cpItem.TypeName, TypeMapping);
	if (cpItem.IsList == true | cpItem.IsArray == true) {
		CreateCppVariable(string.Format("std::vector<{0}>", typeName), cpItem.Name.ToLower());
	} else {
		CreateCppVariable(typeName, cpItem.Name.ToLower());
	}
	if (isNotLast)
		Write(", ");
	
}

protected void CreateCppDeclaration(ClassProperty cpItem, Dictionary<string, string> TypeMapping) 
{
	string typeName = TypeMapper(cpItem.TypeName, TypeMapping);
	if (cpItem.IsList == true | cpItem.IsArray == true) {
		CreateCppVariable(string.Format("std::vector<{0}>", typeName), cpItem.Name); 
	} else {
		CreateCppVariable(typeName, cpItem.Name);
	}
	WriteLine(";");
}

protected void CreateCppVariable(string typeName, string varName) 
{
	Write (string.Format("{0} {1}", typeName, varName)); 
}

protected void CreateCppInitializers(ClassProperty cpItem, bool isNotLast) {
	Write("{0}({1})", cpItem.Name, cpItem.Name.ToLower());
	if (isNotLast)
		Write(", ");
}

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public class CommandGeneratorHBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
