/****************************************************************************************
*
* This code was generated by the Command Creator tool for the ChainsAPM project. 
* If manual changes are made to the code they could be lost.
*
****************************************************************************************/
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ChainsAPM.Commands.Agent
{
    public class DefineMethod : Interfaces.ICommand<byte>
    {

         private Helpers.Fnv1a64 hashhelper;

         public DateTime TimeStamp { get; set; }

        public System.Int64 ModuleID { get; set; }
        public System.Int64 ClassID { get; set; }
        public System.Int64 MethodDef { get; set; }
        public System.Int64 FunctionID { get; set; }
        public System.String MethodName { get; set; }

        public DefineMethod()
        {
            hashhelper = new Helpers.Fnv1a64();
        }

        public DefineMethod(System.Int64 timestamp, System.Int64 _moduleid, System.Int64 _classid, System.Int64 _methoddef, System.Int64 _functionid, System.String _methodname) : this()
        {
            TimeStamp = timestamp == 0 ? DateTime.Now : DateTime.FromFileTimeUtc(timestamp);
            ModuleID = _moduleid;
            ClassID = _classid;
            MethodDef = _methoddef;
            FunctionID = _functionid;
            MethodName = _methodname;
        }

        public string Name
        {
            get { return "Define Method"; }
        }
        public ushort Code
        {
            get { return 0x0005; }
        }
        public string Description
        {
            get { return "Define a method after it has been instrumented. This is required to properly map a mdToken to it's name."; }
        }
        public Type CommandType
        {
            get { return typeof(System.String); }
        }
        public Interfaces.ICommand<byte> Decode(ArraySegment<byte> input)
        {

            if (input.Count != 0)
            {
                Helpers.ArraySegmentStream segstream = new Helpers.ArraySegmentStream(input);
                int size = segstream.GetInt32();
                if (input.Count == size)
                {
                    short code = segstream.GetInt16();
                    if (code == Code)
                    {
                    var timestamp = segstream.GetInt64();
                    var decodeModuleID = segstream.GetInt64();

     
                    var decodeClassID = segstream.GetInt64();

     
                    var decodeMethodDef = segstream.GetInt64();

     
                    var decodeFunctionID = segstream.GetInt64();

     
                    var stringlenMethodName = segstream.GetInt32();
                    var decodeMethodNameHash = segstream.GetInt64();
                    var decodeMethodName = segstream.GetUnicode(stringlenMethodName + 1);

     
                       
                    var term = segstream.GetInt16();

                    if (term != 0)
                    {
                        throw new System.Runtime.Serialization.SerializationException("Terminator is a non zero value. Please check the incoming byte stream for possible errors.");
                    }
                    return new DefineMethod(timestamp, decodeModuleID, decodeClassID, decodeMethodDef, decodeFunctionID, decodeMethodName);
                    }
                    else
                    {
                        throw new System.Runtime.Serialization.SerializationException("Invalid command code detected. Please check the incoming byte stream for possible errors.");
                    }
                }
                else
                {
                    throw new System.Runtime.Serialization.SerializationException("Size of message does not match size of byte stream. Please check the incoming byte stream for possible errors.");
                }
            }
            else
            {
                throw new System.Runtime.Serialization.SerializationException("Size of message is zero. Please check the incoming byte stream for possible errors. ");
            }
        }
        public byte[] Encode()
        {
            int byteSize = 0;

             byteSize += sizeof (Int32); // Length Of Command
             byteSize += sizeof (Int16); // Length Of Code
             byteSize += sizeof (Int64); // Length Of Timestamp

            
            byteSize += sizeof(System.Int64);
            
            byteSize += sizeof(System.Int64);
            
            byteSize += sizeof(System.Int64);
            
            byteSize += sizeof(System.Int64);
            byteSize += sizeof(System.Int32); // Length Bytes
            byteSize += sizeof(System.Int64); // Hash Bytes
            byteSize += MethodName.Length; // StringLength Bytes
            byteSize += sizeof(System.Int16); // Zero Terminated String
            byteSize += sizeof (short); // Length Of Terminator
            var buffer = new List<byte>(byteSize);
            buffer.AddRange(BitConverter.GetBytes(byteSize)); // 4 bytes for size, 2 byte for code, 8 bytes for data, 8 bytes for data, 8 bytes for TS, 2 bytes for term
            buffer.AddRange(BitConverter.GetBytes(Code));
            buffer.AddRange(BitConverter.GetBytes(TimeStamp.ToFileTimeUtc()));
            buffer.AddRange(BitConverter.GetBytes(ModuleID)); 

            buffer.AddRange(BitConverter.GetBytes(ClassID)); 

            buffer.AddRange(BitConverter.GetBytes(MethodDef)); 

            buffer.AddRange(BitConverter.GetBytes(FunctionID)); 

            var sBufferMethodName = System.Text.UnicodeEncoding.Unicode.GetBytes(MethodName);
            buffer.AddRange(BitConverter.GetBytes(MethodName.Length + 1));
            buffer.AddRange(hashhelper.ComputeHash(sBufferMethodName));
            buffer.AddRange(sBufferMethodName);
            buffer.AddRange(BitConverter.GetBytes((short)0));

            buffer.AddRange(BitConverter.GetBytes((short)0));
            return buffer.ToArray();
        }
    }
    
}

