  
  
 

/**************************************************************************************** 
*
* This code was generated by the Command Creator tool for the ChainsAPM project. 
* If manual changes are made to the code they could be lost.
*
****************************************************************************************/
#pragma once
#include "stdafx.h"
#include "commands\DefineModule.h"
 

namespace Commands
{
	DefineModule::DefineModule(__int64 timestamp, __int64 moduleid, std::wstring modulename)
		: timestamp(timestamp), code(0x0004), hasEncoded(false), ModuleID(moduleid), ModuleName(modulename) 
	{
	}

	DefineModule::~DefineModule()
	{
	}

	std::wstring DefineModule::Name()
	{
		return L"Define Module";
	}

	std::wstring DefineModule::Description()
	{
		return L"Define a module after it has been loaded. This is required to properly map a mdToken to it's name.";
	}

	std::shared_ptr<std::vector<char>> DefineModule::Encode()
	{
		if (!hasEncoded)
		{
			// The following items will be resued 
			auto hash = std::hash<std::wstring>();
			size_t hashout = 0;		// Temp var for string hashes
			size_t strlen = 0;		// Temp var for string length
			size_t strbytes = 0;	// Temp var for string bytes

			size_t size = sizeof(__int32)	// len
				+ sizeof(short)				// code
				+ sizeof(__int64);			// timestamp

			// Begin the dynamically generated sizes
			size += sizeof(__int64); // Size of ModuleID
			
			size_t strlen_ModuleNamelen = ModuleName.length();
			size_t strbytes_ModuleNamelen = (strlen_ModuleNamelen * sizeof(wchar_t)) + sizeof(wchar_t);
			size += sizeof(__int32); // String Length 
			size += sizeof(__int64); // String Hash
			size += strbytes_ModuleNamelen; // String Bytes

			// End the dynamically generated sizes  
			size += sizeof(short);	//Terminator

			auto vector = new char[size]; 
			short term = 0;
			
			// 
			auto v2 = (char*)memcpy(vector, &size, sizeof(__int32));  
			v2 += sizeof(__int32); 
			memcpy(v2, &code, sizeof(short));
			v2 += sizeof(short);
			memcpy(v2, &timestamp, sizeof(__int64));
			v2 += sizeof(__int64);

			// Begin the dynamically generated byte copies    
			memcpy(v2, &ModuleID, sizeof(__int64));  
			v2 += sizeof(__int64); size_t strlen_ModuleNamedata = ModuleName.length();
			size_t strbytes_ModuleNamedata = (strlen_ModuleNamedata * sizeof(wchar_t)) + sizeof(wchar_t);
			hashout = hash(ModuleName);
			 
			
			memcpy(v2, &strlen_ModuleNamedata, sizeof(__int32));
			v2 += sizeof(__int32);
			memcpy(v2, &hashout, sizeof(size_t));
			v2 += sizeof(__int64);
			memcpy(v2, ModuleName.data(), strbytes_ModuleNamedata);
			v2 += strbytes_ModuleNamedata;
			// End the dynamically generated byte copies

			// Terminator
			memcpy(v2, &term, sizeof(short));
			v2 += sizeof(short);

			hasEncoded = true;

			internalvector = std::make_shared<std::vector<char>>(vector, v2);
		}
		return internalvector;
	}

	std::shared_ptr<ICommand> DefineModule::Decode(std::shared_ptr<std::vector<char>> &data)      
	{
		auto hash = std::hash<std::wstring>();

		auto ptr = data->data();

		auto len = *(unsigned int*)ptr;  
		ptr += sizeof(unsigned int);

		auto code = *(short*)ptr;
		ptr += sizeof(short);

		auto local_timestamp = *(__int64*)ptr;
		ptr += sizeof(__int64);

		auto local_ModuleID = *(__int64*)ptr;  
		ptr += sizeof(__int64); 
		
		auto strlenModuleName = *(__int32*)ptr;
		ptr += sizeof(__int32);
		
		auto hashModuleName = *(__int64*)ptr;
		ptr += sizeof(__int64);
		
		auto local_ModuleName = (wchar_t*)ptr;
		ptr += strlenModuleName * 2;

		// Terminator
		auto term = *(short*)ptr;
		ptr += sizeof(short);
		return std::make_shared<DefineModule>(local_timestamp,  local_ModuleID ,  local_ModuleName );
	}
}

