  
  
 

/**************************************************************************************** 
*
* This code was generated by the Command Creator tool for the ChainsAPM project. 
* If manual changes are made to the code they could be lost.
*
****************************************************************************************/
#pragma once
#include "stdafx.h"
#include "commands\DefineMethod.h"
 

namespace Commands
{
	DefineMethod::DefineMethod(__int64 timestamp, __int64 moduleid, __int64 classid, __int64 methoddef, __int64 functionid, std::wstring methodname)
		: timestamp(timestamp), code(0x0005), hasEncoded(false), ModuleID(moduleid), ClassID(classid), MethodDef(methoddef), FunctionID(functionid), MethodName(methodname) 
	{
	}

	DefineMethod::~DefineMethod()
	{
	}

	std::wstring DefineMethod::Name()
	{
		return L"Define Method";
	}

	std::wstring DefineMethod::Description()
	{
		return L"Define a method after it has been instrumented. This is required to properly map a mdToken to it's name.";
	}

	std::shared_ptr<std::vector<char>> DefineMethod::Encode()
	{
		if (!hasEncoded)
		{
			// The following items will be resued 
			auto hash = std::hash<std::wstring>();
			size_t hashout = 0;		// Temp var for string hashes
			size_t strlen = 0;		// Temp var for string length
			size_t strbytes = 0;	// Temp var for string bytes

			size_t size = sizeof(__int32)	// len
				+ sizeof(short)				// code
				+ sizeof(__int64);			// timestamp

			// Begin the dynamically generated sizes
			size += sizeof(__int64); // Size of ModuleID
			
			size += sizeof(__int64); // Size of ClassID
			
			size += sizeof(__int64); // Size of MethodDef
			
			size += sizeof(__int64); // Size of FunctionID
			
			size_t strlen_MethodNamelen = MethodName.length();
			size_t strbytes_MethodNamelen = (strlen_MethodNamelen * sizeof(wchar_t)) + sizeof(wchar_t);
			size += sizeof(__int32); // String Length 
			size += sizeof(__int64); // String Hash
			size += strbytes_MethodNamelen; // String Bytes

			// End the dynamically generated sizes  
			size += sizeof(short);	//Terminator

			auto vector = new char[size]; 
			short term = 0;
			
			// 
			auto v2 = (char*)memcpy(vector, &size, sizeof(__int32));  
			v2 += sizeof(__int32); 
			memcpy(v2, &code, sizeof(short));
			v2 += sizeof(short);
			memcpy(v2, &timestamp, sizeof(__int64));
			v2 += sizeof(__int64);

			// Begin the dynamically generated byte copies    
			memcpy(v2, &ModuleID, sizeof(__int64));  
			v2 += sizeof(__int64); memcpy(v2, &ClassID, sizeof(__int64));  
			v2 += sizeof(__int64); memcpy(v2, &MethodDef, sizeof(__int64));  
			v2 += sizeof(__int64); memcpy(v2, &FunctionID, sizeof(__int64));  
			v2 += sizeof(__int64); size_t strlen_MethodNamedata = MethodName.length();
			size_t strbytes_MethodNamedata = (strlen_MethodNamedata * sizeof(wchar_t)) + sizeof(wchar_t);
			hashout = hash(MethodName);
			 
			
			memcpy(v2, &strlen_MethodNamedata, sizeof(__int32));
			v2 += sizeof(__int32);
			memcpy(v2, &hashout, sizeof(size_t));
			v2 += sizeof(__int64);
			memcpy(v2, MethodName.data(), strbytes_MethodNamedata);
			v2 += strbytes_MethodNamedata;
			// End the dynamically generated byte copies

			// Terminator
			memcpy(v2, &term, sizeof(short));
			v2 += sizeof(short);

			hasEncoded = true;

			internalvector = std::make_shared<std::vector<char>>(vector, v2);
		}
		return internalvector;
	}

	std::shared_ptr<ICommand> DefineMethod::Decode(std::shared_ptr<std::vector<char>> &data)      
	{
		auto hash = std::hash<std::wstring>();

		auto ptr = data->data();

		auto len = *(unsigned int*)ptr;  
		ptr += sizeof(unsigned int);

		auto code = *(short*)ptr;
		ptr += sizeof(short);

		auto local_timestamp = *(__int64*)ptr;
		ptr += sizeof(__int64);

		auto local_ModuleID = *(__int64*)ptr;  
		ptr += sizeof(__int64); 
		auto local_ClassID = *(__int64*)ptr;  
		ptr += sizeof(__int64); 
		auto local_MethodDef = *(__int64*)ptr;  
		ptr += sizeof(__int64); 
		auto local_FunctionID = *(__int64*)ptr;  
		ptr += sizeof(__int64); 
		
		auto strlenMethodName = *(__int32*)ptr;
		ptr += sizeof(__int32);
		
		auto hashMethodName = *(__int64*)ptr;
		ptr += sizeof(__int64);
		
		auto local_MethodName = (wchar_t*)ptr;
		ptr += strlenMethodName * 2;

		// Terminator
		auto term = *(short*)ptr;
		ptr += sizeof(short);
		return std::make_shared<DefineMethod>(local_timestamp,  local_ModuleID ,  local_ClassID ,  local_MethodDef ,  local_FunctionID ,  local_MethodName );
	}
}

