  
  
 

/**************************************************************************************** 
*
* This code was generated by the Command Creator tool for the ChainsAPM project. 
* If manual changes are made to the code they could be lost.
*
****************************************************************************************/
#pragma once
#include "stdafx.h"
#include "commands\MethodEnter.h"
 

namespace Commands
{
	MethodEnter::MethodEnter(__int64 timestamp, __int64 threadid, __int64 moduleid, __int64 methoddef)
		: timestamp(timestamp), code(0x0006), hasEncoded(false), ThreadID(threadid), ModuleID(moduleid), MethodDef(methoddef) 
	{
	}

	MethodEnter::~MethodEnter()
	{
	}

	std::wstring MethodEnter::Name()
	{
		return L"Method Enter";
	}

	std::wstring MethodEnter::Description()
	{
		return L"Update Command Description";
	}

	std::shared_ptr<std::vector<char>> MethodEnter::Encode()
	{
		if (!hasEncoded)
		{
			// The following items will be resued 
			auto hash = std::hash<std::wstring>();
			size_t hashout = 0;		// Temp var for string hashes
			size_t strlen = 0;		// Temp var for string length
			size_t strbytes = 0;	// Temp var for string bytes

			size_t size = sizeof(__int32)	// len
				+ sizeof(short)				// code
				+ sizeof(__int64);			// timestamp

			// Begin the dynamically generated sizes
			size += sizeof(__int64); // Size of ThreadID
			
			size += sizeof(__int64); // Size of ModuleID
			
			size += sizeof(__int64); // Size of MethodDef
			
			// End the dynamically generated sizes  
			size += sizeof(short);	//Terminator

			auto vector = new char[size]; 
			short term = 0;
			
			// 
			auto v2 = (char*)memcpy(vector, &size, sizeof(__int32));  
			v2 += sizeof(__int32); 
			memcpy(v2, &code, sizeof(short));
			v2 += sizeof(short);
			memcpy(v2, &timestamp, sizeof(__int64));
			v2 += sizeof(__int64);

			// Begin the dynamically generated byte copies    
			memcpy(v2, &ThreadID, sizeof(__int64));  
			v2 += sizeof(__int64); memcpy(v2, &ModuleID, sizeof(__int64));  
			v2 += sizeof(__int64); memcpy(v2, &MethodDef, sizeof(__int64));  
			v2 += sizeof(__int64); 			// End the dynamically generated byte copies

			// Terminator
			memcpy(v2, &term, sizeof(short));
			v2 += sizeof(short);

			hasEncoded = true;

			internalvector = std::make_shared<std::vector<char>>(vector, v2);
		}
		return internalvector;
	}

	std::shared_ptr<ICommand> MethodEnter::Decode(std::shared_ptr<std::vector<char>> &data)      
	{
		auto hash = std::hash<std::wstring>();

		auto ptr = data->data();

		auto len = *(unsigned int*)ptr;  
		ptr += sizeof(unsigned int);

		auto code = *(short*)ptr;
		ptr += sizeof(short);

		auto local_timestamp = *(__int64*)ptr;
		ptr += sizeof(__int64);

		auto local_ThreadID = *(__int64*)ptr;  
		ptr += sizeof(__int64); 
		auto local_ModuleID = *(__int64*)ptr;  
		ptr += sizeof(__int64); 
		auto local_MethodDef = *(__int64*)ptr;  
		ptr += sizeof(__int64); 

		// Terminator
		auto term = *(short*)ptr;
		ptr += sizeof(short);
		return std::make_shared<MethodEnter>(local_timestamp,  local_ThreadID ,  local_ModuleID ,  local_MethodDef );
	}
}

